title = "Ronald Farias"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "hugo-future-imperfect-slim"

defaultMarkdownHandler = "blackfriday"
MetaDataFormat = "yaml"
DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
paginate = 100 # this is set low for demonstrating with dummy content. Set to a higher number
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClasses = true
[Taxonomies]
  tag = "tags"
summaryLength = 30
[markup]

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4


[languages]
    [languages.en]
        weight = 1
        contentDir = "content/en"
    [languages.pt]
        weight = 2
        contentDir = "content/pt"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  featured_image = "images/tandem-x-visuals-unsplash.jpg"
  recent_posts_number = 2
  post_content_classes = ""
  body_classes = "avenir"
  disqusShortname = "YOURSHORTNAME"
  sectionPagesMenu = "main"
  homepage_image = "images/tandem-x-visuals-unsplash.jpg"
  homepage_intro = "Wellcome adventurer. Read some use(less)full IT articles and keep enjoying your travel."
  homepage_button_link = '/posts'
  homepage_button_text = 'Read The Posts'
  custom_css = ['css/code.css']