baseURL                   = "http://www.ronald.dev.br/"
builddrafts                = false
defaultContentLanguage     = "en-us"
languageCode               = "en-us"
# defaultContentLanguageInSubdir = true
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Ronald Rodrigues | IT Blog"

pygmentsuseclasses         = true

[languages]

  [languages.en]
    contentDir = "content/en"
    title = "IT | The Blog"
    languageName = "English"
    languageCode = "en-us"
    welcome_head             = "Hi, adventurer!"
    welcome_word             = "~ Grabe your drink and move on ~"
    weight = 0

    [[languages.en.menu.main]]
      name                   = "Blog"
      weight                 = 0
      identifier             = "blog"
      url                    = "blog/"

    [[languages.en.menu.main]]
      name                   = "Moment"
      weight                 = 0
      identifier             = "moment"
      url                    = "moment/"

    [[languages.en.menu.main]]
      name                   = "About"
      weight                 = 0
      identifier             = "about"
      url                    = "about/"

  [languages.pt]
    contentDir = "content/pt"
    title = "IT | O Blog"
    languageName = "Portuguese"
    languageCode = "pt"
    weight = 10
    welcome_head             = "Oi, aventureiro!"
    welcome_word             = "~ Pegue sua bebida e siga em frente ~"


    [[Languages.pt.menu.main]]
      name              = "Blog"
      identifier        = "Blog"
      url               = "pt/blog/"
      weight            = 10

    [[Languages.pt.menu.main]]
      name              = "Momentos"
      identifier        = "moment"
      url               = "moment/"
      weight            = 10

    [[Languages.pt.menu.main]]
      name              = "Sobre"
      weight            = 10
      identifier        = "about"
      url               = "pt/about/"

[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  name = "en"
  [[menu.main]]
    name                   = "home"
    weight                 = -120
    identifier             = "Home"
    url                    = "/"

  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/"

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"


 

[params]
  faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "img/saitama.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Ronald Rodrigues"
  description              = ["Software Engineer", "Writting some stuff posts", "and sharing my love or hate by the things."]           # appears in the site header when set to a non-empty string

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "ronald-farias@outlook.com"
  github                   = "//github.com/ronald-tr"
  linkedin                 = "//linkedin.com/in/ronald-rodrigues-farias-aa4313a3"
  twitter                  = "//twitter.com/ronaldrfarias" 
  instagram                = "//instagram.com/ronaldrodriguesfarias"
  # include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    